version: "3.2"

services:
  app: 
    build: .
    environment:
      - MONGO_URI=mongodb://localhost:27017/pokemon
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes: 
      - ./data:/data/db